// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igenkbdgctezmzicxhgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnZW5rYmRnY3Rlem16aWN4aGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMTk3ODUsImV4cCI6MjA3MDc5NTc4NX0._p5ZRHOOaNLsdOB65Ixr7uanRXY8QGS1wTlLhiGSVvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});